# Permalinks
permalink:           pretty

# Setup
title:               Fanger's
tagline:             Data Science Blog
url:                 http://robcfang.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Robert C Fang
  url:               https://robcfang.com
  email:             robcfang@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/robcfang

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
